version: "3.4"
services:
  apache:
    build: './docker/apache/'
    container_name: sm-apache
    restart: always
    depends_on:
      - php
      - mariadb
      - supervisor
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html/
  php:
    build:
      context: './docker/php/'
      target: php
    container_name: sm-php
    restart: always
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  cronjob:
    build:
      context: './docker/php/'
      target: cron
    container_name: sm-cronjob
    restart: always
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  supervisor:
      build:
        context: './docker/php/'
        target: queue
      container_name: sm-supervisor
      networks:
        - backend
      volumes:
        - ./:/var/www/html/
        - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  mariadb:
    image: mariadb
    container_name: sm-mariadb
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stocks-market
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sm-phpmyadmin
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mariadb
      - PMA_PORT=3306

    restart: always
    ports:
      - "8889:80"
    networks:
      - backend

networks:
  frontend:
  backend:
